export const balkanCountryPresets = [
  {
    code: 'AL',
    flag: '🇦🇱',
    flagImage: 'https://flagcdn.com/w80/al.png',
    name: 'Albania',
    mapPosition: { x: 56, y: 34 },
    coordinates: [41.3275, 19.8189],
    cities: ['Tirana', 'Durres', 'Vlore', 'Shkoder'],
    queries: ['baby clothing store', 'kids clothing store', 'dyqan rrobash femijesh'],
  },
  {
    code: 'BA',
    flag: '🇧🇦',
    flagImage: 'https://flagcdn.com/w80/ba.png',
    name: 'Bosnia and Herzegovina',
    mapPosition: { x: 54, y: 28 },
    coordinates: [43.8563, 18.4131],
    cities: ['Sarajevo', 'Banja Luka', 'Mostar', 'Tuzla'],
    queries: ['baby clothing store', 'kids clothing store', 'prodavnica dječije odjeće'],
  },
  {
    code: 'BG',
    flag: '🇧🇬',
    flagImage: 'https://flagcdn.com/w80/bg.png',
    name: 'Bulgaria',
    mapPosition: { x: 62, y: 30 },
    coordinates: [42.6977, 23.3219],
    cities: ['Sofia', 'Plovdiv', 'Varna', 'Burgas'],
    queries: ['baby clothing store', 'kids clothing store', 'детски дрехи магазин'],
  },
  {
    code: 'HR',
    flag: '🇭🇷',
    flagImage: 'https://flagcdn.com/w80/hr.png',
    name: 'Croatia',
    mapPosition: { x: 54, y: 24 },
    coordinates: [45.815, 15.9819],
    cities: ['Zagreb', 'Split', 'Rijeka', 'Osijek'],
    queries: ['baby clothing store', 'kids clothing store', 'trgovina dječje odjeće'],
  },
  {
    code: 'GR',
    flag: '🇬🇷',
    flagImage: 'https://flagcdn.com/w80/gr.png',
    name: 'Greece',
    mapPosition: { x: 61, y: 39 },
    coordinates: [37.9838, 23.7275],
    cities: ['Athens', 'Thessaloniki', 'Patras', 'Heraklion'],
    queries: ['baby clothing store', 'kids clothing store', 'κατάστημα παιδικών ρούχων'],
  },
  {
    code: 'XK',
    flag: '🇽🇰',
    flagImage: 'https://flagcdn.com/w80/xk.png',
    name: 'Kosovo',
    mapPosition: { x: 58, y: 32 },
    coordinates: [42.6629, 21.1655],
    cities: ['Pristina', 'Prizren', 'Peja', 'Gjilan'],
    queries: ['baby clothing store', 'kids clothing store', 'dyqan rrobash per femije'],
  },
  {
    code: 'ME',
    flag: '🇲🇪',
    flagImage: 'https://flagcdn.com/w80/me.png',
    name: 'Montenegro',
    mapPosition: { x: 55, y: 31 },
    coordinates: [42.4304, 19.2594],
    cities: ['Podgorica', 'Niksic', 'Budva', 'Bar'],
    queries: ['baby clothing store', 'kids clothing store', 'prodavnica dječije odjeće'],
  },
  {
    code: 'MK',
    flag: '🇲🇰',
    flagImage: 'https://flagcdn.com/w80/mk.png',
    name: 'North Macedonia',
    mapPosition: { x: 60, y: 35 },
    coordinates: [41.9981, 21.4254],
    cities: ['Skopje', 'Bitola', 'Kumanovo', 'Ohrid'],
    queries: ['baby clothing store', 'kids clothing store', 'продавница за детска облека'],
  },
  {
    code: 'RO',
    flag: '🇷🇴',
    flagImage: 'https://flagcdn.com/w80/ro.png',
    name: 'Romania',
    mapPosition: { x: 61, y: 22 },
    coordinates: [44.4268, 26.1025],
    cities: ['Bucharest', 'Cluj-Napoca', 'Iasi', 'Timisoara', 'Constanta'],
    queries: ['baby clothing store', 'kids clothing store', 'haine copii', 'magazin haine copii'],
  },
  {
    code: 'RS',
    flag: '🇷🇸',
    flagImage: 'https://flagcdn.com/w80/rs.png',
    name: 'Serbia',
    mapPosition: { x: 57, y: 28 },
    coordinates: [44.7866, 20.4489],
    cities: ['Belgrade', 'Novi Sad', 'Nis', 'Kragujevac'],
    queries: ['baby clothing store', 'kids clothing store', 'prodavnica dečije odeće'],
  },
  {
    code: 'SI',
    flag: '🇸🇮',
    flagImage: 'https://flagcdn.com/w80/si.png',
    name: 'Slovenia',
    mapPosition: { x: 52, y: 22 },
    coordinates: [46.0569, 14.5058],
    cities: ['Ljubljana', 'Maribor', 'Celje', 'Koper'],
    queries: ['baby clothing store', 'kids clothing store', 'trgovina otroških oblačil'],
  },
  {
    code: 'TR',
    flag: '🇹🇷',
    flagImage: 'https://flagcdn.com/w80/tr.png',
    name: 'Turkey',
    mapPosition: { x: 67, y: 35 },
    coordinates: [39.9334, 32.8597],
    cities: ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya'],
    queries: ['baby clothing store', 'kids clothing store', 'bebek giyim mağazası', 'çocuk giyim mağazası'],
  },
  {
    code: 'UA',
    flag: '🇺🇦',
    flagImage: 'https://flagcdn.com/w80/ua.png',
    name: 'Ukraine',
    mapPosition: { x: 62, y: 20 },
    coordinates: [50.4501, 30.5234],
    cities: ['Kyiv', 'Lviv', 'Odesa', 'Dnipro', 'Kharkiv'],
    queries: ['baby clothing store', 'kids clothing store', 'дитячий одяг магазин', 'одяг для немовлят магазин'],
  },
  {
    code: 'RU',
    flag: '🇷🇺',
    flagImage: 'https://flagcdn.com/w80/ru.png',
    name: 'Russia',
    mapPosition: { x: 68, y: 16 },
    coordinates: [55.7558, 37.6173],
    cities: ['Moscow', 'Saint Petersburg', 'Kazan', 'Yekaterinburg', 'Novosibirsk'],
    queries: ['baby clothing store', 'kids clothing store', 'магазин детской одежды', 'магазин одежды для малышей'],
  },
  {
    code: 'MD',
    flag: '🇲🇩',
    flagImage: 'https://flagcdn.com/w80/md.png',
    name: 'Moldova',
    mapPosition: { x: 60, y: 23 },
    coordinates: [47.0105, 28.8638],
    cities: ['Chisinau', 'Balti', 'Tiraspol', 'Bender'],
    queries: ['baby clothing store', 'kids clothing store', 'magazin haine copii', 'haine pentru bebelusi'],
  },
  {
    code: 'PL',
    flag: '🇵🇱',
    flagImage: 'https://flagcdn.com/w80/pl.png',
    name: 'Poland',
    mapPosition: { x: 56, y: 18 },
    coordinates: [52.2297, 21.0122],
    cities: ['Warsaw', 'Krakow', 'Wroclaw', 'Gdansk', 'Poznan'],
    queries: ['baby clothing store', 'kids clothing store', 'sklep z odzieżą dziecięcą', 'ubranka dla niemowląt sklep'],
  },
  {
    code: 'BY',
    flag: '🇧🇾',
    flagImage: 'https://flagcdn.com/w80/by.png',
    name: 'Belarus',
    mapPosition: { x: 59, y: 17 },
    coordinates: [53.9006, 27.559],
    cities: ['Minsk', 'Gomel', 'Grodno', 'Brest', 'Vitebsk'],
    queries: ['baby clothing store', 'kids clothing store', 'магазин детской одежды', 'адзенне для дзяцей крама'],
  },
  {
    code: 'GE',
    flag: '🇬🇪',
    flagImage: 'https://flagcdn.com/w80/ge.png',
    name: 'Georgia',
    mapPosition: { x: 65, y: 32 },
    coordinates: [41.7151, 44.8271],
    cities: ['Tbilisi', 'Batumi', 'Kutaisi', 'Rustavi'],
    queries: ['baby clothing store', 'kids clothing store', 'ბავშვის ტანსაცმლის მაღაზია', 'საბავშვო ტანსაცმელი'],
  },
  {
    code: 'AM',
    flag: '🇦🇲',
    flagImage: 'https://flagcdn.com/w80/am.png',
    name: 'Armenia',
    mapPosition: { x: 66, y: 34 },
    coordinates: [40.1792, 44.4991],
    cities: ['Yerevan', 'Gyumri', 'Vanadzor', 'Abovyan'],
    queries: ['baby clothing store', 'kids clothing store', 'մանկական հագուստի խանութ', 'երեխաների հագուստ'],
  },
  {
    code: 'AZ',
    flag: '🇦🇿',
    flagImage: 'https://flagcdn.com/w80/az.png',
    name: 'Azerbaijan',
    mapPosition: { x: 68, y: 34 },
    coordinates: [40.4093, 49.8671],
    cities: ['Baku', 'Ganja', 'Sumqayit', 'Mingachevir'],
    queries: ['baby clothing store', 'kids clothing store', 'uşaq geyim mağazası', 'körpə geyim mağazası'],
  },
  {
    code: 'KZ',
    flag: '🇰🇿',
    flagImage: 'https://flagcdn.com/w80/kz.png',
    name: 'Kazakhstan',
    mapPosition: { x: 75, y: 25 },
    coordinates: [51.1694, 71.4491],
    cities: ['Astana', 'Almaty', 'Shymkent', 'Karaganda', 'Aktobe'],
    queries: ['baby clothing store', 'kids clothing store', 'магазин детской одежды', 'балалар киімі дүкені'],
  },
  {
    code: 'UZ',
    flag: '🇺🇿',
    flagImage: 'https://flagcdn.com/w80/uz.png',
    name: 'Uzbekistan',
    mapPosition: { x: 74, y: 34 },
    coordinates: [41.2995, 69.2401],
    cities: ['Tashkent', 'Samarkand', 'Bukhara', 'Namangan', 'Andijan'],
    queries: ['baby clothing store', 'kids clothing store', 'bolalar kiyim doʻkoni', 'chaqaloq kiyim doʻkoni'],
  },
  {
    code: 'KG',
    flag: '🇰🇬',
    flagImage: 'https://flagcdn.com/w80/kg.png',
    name: 'Kyrgyzstan',
    mapPosition: { x: 78, y: 34 },
    coordinates: [42.8746, 74.5698],
    cities: ['Bishkek', 'Osh', 'Jalal-Abad', 'Karakol'],
    queries: ['baby clothing store', 'kids clothing store', 'магазин детской одежды', 'балдар кийим дүкөнү'],
  },
  {
    code: 'TJ',
    flag: '🇹🇯',
    flagImage: 'https://flagcdn.com/w80/tj.png',
    name: 'Tajikistan',
    mapPosition: { x: 78, y: 38 },
    coordinates: [38.5598, 68.787],
    cities: ['Dushanbe', 'Khujand', 'Kulob', 'Bokhtar'],
    queries: ['baby clothing store', 'kids clothing store', 'магазин детской одежды', 'либоси кӯдакона мағоза'],
  },
  {
    code: 'TM',
    flag: '🇹🇲',
    flagImage: 'https://flagcdn.com/w80/tm.png',
    name: 'Turkmenistan',
    mapPosition: { x: 72, y: 36 },
    coordinates: [37.9601, 58.3261],
    cities: ['Ashgabat', 'Turkmenabat', 'Dashoguz', 'Mary', 'Balkanabat'],
    queries: ['baby clothing store', 'kids clothing store', 'çaga eşikleri dükany', 'магазин детской одежды'],
  },
  {
    code: 'RU-DA',
    flag: '🇷🇺',
    flagImage: 'https://flagcdn.com/w80/ru.png',
    name: 'Dagestan (Russia)',
    mapPosition: { x: 68, y: 33 },
    coordinates: [42.9849, 47.5047],
    cities: ['Makhachkala', 'Derbent', 'Khasavyurt', 'Kaspiysk'],
    queries: ['baby clothing store', 'kids clothing store', 'магазин детской одежды', 'детская одежда Махачкала'],
  },
  {
    code: 'RU-CE',
    flag: '🇷🇺',
    flagImage: 'https://flagcdn.com/w80/ru.png',
    name: 'Chechnya (Russia)',
    mapPosition: { x: 67, y: 33 },
    coordinates: [43.318, 45.6986],
    cities: ['Grozny', 'Argun', 'Gudermes', 'Urus-Martan'],
    queries: ['baby clothing store', 'kids clothing store', 'магазин детской одежды', 'детская одежда Грозный'],
  },
  {
    code: 'RU-IN',
    flag: '🇷🇺',
    flagImage: 'https://flagcdn.com/w80/ru.png',
    name: 'Ingushetia (Russia)',
    mapPosition: { x: 66, y: 33 },
    coordinates: [43.1668, 44.8036],
    cities: ['Magas', 'Nazran', 'Malgobek', 'Karabulak'],
    queries: ['baby clothing store', 'kids clothing store', 'магазин детской одежды', 'детская одежда Назрань'],
  },
  {
    code: 'RU-SE',
    flag: '🇷🇺',
    flagImage: 'https://flagcdn.com/w80/ru.png',
    name: 'North Ossetia (Russia)',
    mapPosition: { x: 65, y: 33 },
    coordinates: [43.0241, 44.6819],
    cities: ['Vladikavkaz', 'Mozdok', 'Beslan', 'Alagir'],
    queries: ['baby clothing store', 'kids clothing store', 'магазин детской одежды', 'детская одежда Владикавказ'],
  },
  {
    code: 'RU-TA',
    flag: '🇷🇺',
    flagImage: 'https://flagcdn.com/w80/ru.png',
    name: 'Tatarstan (Russia)',
    mapPosition: { x: 67, y: 21 },
    coordinates: [55.8304, 49.0661],
    cities: ['Kazan', 'Naberezhnye Chelny', 'Nizhnekamsk', 'Almetyevsk'],
    queries: ['baby clothing store', 'kids clothing store', 'магазин детской одежды', 'балалар киеме кибете'],
  },
  {
    code: 'RU-BA',
    flag: '🇷🇺',
    flagImage: 'https://flagcdn.com/w80/ru.png',
    name: 'Bashkortostan (Russia)',
    mapPosition: { x: 69, y: 22 },
    coordinates: [54.7388, 55.9721],
    cities: ['Ufa', 'Sterlitamak', 'Salavat', 'Neftekamsk'],
    queries: ['baby clothing store', 'kids clothing store', 'магазин детской одежды', 'детская одежда Уфа'],
  },
];
