export const countryMarketProfiles = {
  AL: {
    population: 2377128,
    populationYear: 2024,
    gdpPerCapitaUsd: 11378,
    gdpYear: 2024,
    tradeSummary: 'Küçük ama ithalata açık pazar. Tirana ve kıyı şehirleri perakende keşfi için öncelikli.',
    babyKidsClothingSignal: 'Butik çocuk giyim, uygun fiyatlı ithal ürün ve sosyal medya üzerinden satış yaygın.',
    salesNotes: ['Tirana ilk pilot şehir olmalı.', 'WhatsApp ve Instagram teması hızlı dönüş sağlayabilir.', 'Küçük minimum sipariş avantaj yaratır.'],
  },
  BA: {
    population: 3164253,
    populationYear: 2024,
    gdpPerCapitaUsd: 9359,
    gdpYear: 2024,
    tradeSummary: 'Dağınık şehir yapısı olan, fiyat hassasiyeti yüksek ve bölgesel perakendecilerle çalışan pazar.',
    babyKidsClothingSignal: 'Çocuk giyim mağazaları genelde şehir merkezlerinde yoğunlaşır; uygun fiyat ve güvenilir tedarik öne çıkar.',
    salesNotes: ['Sarajevo ve Banja Luka ayrı ayrı taranmalı.', 'Boşnakça/Sırpça/Hırvatça arama terimleri birlikte kullanılmalı.', 'Toptan teklif sade ve fiyat odaklı olmalı.'],
  },
  BG: {
    population: 6441421,
    populationYear: 2024,
    gdpPerCapitaUsd: 17596,
    gdpYear: 2024,
    tradeSummary: 'AB üyesi, lojistik olarak Türkiye’ye yakın ve ithalat/toptan bağlantıları güçlü pazar.',
    babyKidsClothingSignal: 'Sofia, Plovdiv ve Varna bebek/çocuk giyim mağazası keşfi için güçlü başlangıç noktaları.',
    salesNotes: ['Bulgarca keywordler mutlaka kullanılmalı.', 'Sofia sonrası Plovdiv ve Varna hızlı ikinci dalga olabilir.', 'AB içi kalite/etiket beklentileri not edilmeli.'],
  },
  HR: {
    population: 3866200,
    populationYear: 2024,
    gdpPerCapitaUsd: 24050,
    gdpYear: 2024,
    tradeSummary: 'AB ve Euro bölgesi içinde, alım gücü Balkan ortalamasına göre daha yüksek bir perakende pazarı.',
    babyKidsClothingSignal: 'Zagreb ve sahil şehirlerinde butik, sezonluk ve kalite odaklı çocuk giyim talebi izlenebilir.',
    salesNotes: ['Zagreb ana pilot olmalı.', 'Ürün fotoğrafı ve katalog kalitesi önemli.', 'Euro fiyat listesi hazırlamak faydalı olur.'],
  },
  GR: {
    population: 10405134,
    populationYear: 2024,
    gdpPerCapitaUsd: 24626,
    gdpYear: 2024,
    tradeSummary: 'Büyük nüfus, turizm etkisi ve şehir bazlı perakende yoğunluğu olan Akdeniz pazarı.',
    babyKidsClothingSignal: 'Athens ve Thessaloniki çocuk giyim mağazası taraması için en yüksek hacimli başlangıç şehirleri.',
    salesNotes: ['Yunanca keywordler dönüşümü artırır.', 'Sezonluk ürün planı önemli.', 'Site ve Instagram bulunan mağazalar önceliklenmeli.'],
  },
  XK: {
    population: 1594353,
    populationYear: 2024,
    gdpPerCapitaUsd: 7023,
    gdpYear: 2024,
    tradeSummary: 'Küçük nüfuslu, fiyat hassasiyeti olan ve yakın bölge tedarikçilerine açık gelişen pazar.',
    babyKidsClothingSignal: 'Pristina ve Prizren butik/perakende çocuk giyim keşfi için en mantıklı ilk iki şehir.',
    salesNotes: ['Arnavutça arama terimleri kullanılmalı.', 'Küçük parti ve hızlı teslimat avantajlıdır.', 'Instagram varlığı sıcak lead sinyali sayılmalı.'],
  },
  ME: {
    population: 623525,
    populationYear: 2024,
    gdpPerCapitaUsd: 13263,
    gdpYear: 2024,
    tradeSummary: 'Çok küçük fakat turizm etkisi olan, şehir bazlı niş perakende fırsatları sunan pazar.',
    babyKidsClothingSignal: 'Podgorica ana merkez; Budva ve Bar sezonluk çocuk giyim talebi için izlenebilir.',
    salesNotes: ['Lead sayısı az ama kalite odaklı değerlendirme yapılmalı.', 'Turistik şehirlerde sezon notu tutulmalı.', 'Minimum sipariş düşük tutulmalı.'],
  },
  MK: {
    population: 1824359,
    populationYear: 2024,
    gdpPerCapitaUsd: 9292,
    gdpYear: 2024,
    tradeSummary: 'Kompakt, fiyat duyarlı ve bölgesel tedarik alternatiflerine açık bir Balkan pazarı.',
    babyKidsClothingSignal: 'Skopje güçlü başlangıç noktası; Bitola ve Kumanovo ikinci dalga için uygun.',
    salesNotes: ['Makedonca keywordler kullanılmalı.', 'Skopje leadleri elle kalite kontrolünden geçmeli.', 'WhatsApp iletişimi öncelikli olabilir.'],
  },
  RO: {
    population: 19051804,
    populationYear: 2024,
    gdpPerCapitaUsd: 20080,
    gdpYear: 2024,
    tradeSummary: 'Bölgedeki en büyük AB pazarlarından biri; şehir ölçeği ve mağaza sayısı lead üretimi için güçlü.',
    babyKidsClothingSignal: 'Bucharest, Cluj-Napoca, Iasi ve Timisoara bebek/çocuk giyim için yüksek potansiyelli şehirler.',
    salesNotes: ['Romence keywordler mutlaka çalıştırılmalı.', 'Bucharest pilot sonrası şehir şehir genişlemek mantıklı.', 'Website ve telefon bulunan mağazalar sıcak kabul edilmeli.'],
  },
  RS: {
    population: 6586476,
    populationYear: 2024,
    gdpPerCapitaUsd: 13679,
    gdpYear: 2024,
    tradeSummary: 'Bölgesel ticaret merkezi etkisi olan, Belgrade ve Novi Sad etrafında yoğunlaşan pazar.',
    babyKidsClothingSignal: 'Belgrade en yüksek lead hacmini verir; Novi Sad kalite/orta segment mağazalar için takip edilmeli.',
    salesNotes: ['Sırpça keywordler kullanılmalı.', 'Belgrade leadleri segmentlere ayrılmalı.', 'Fiyat ve teslim süresi net yazılmalı.'],
  },
  SI: {
    population: 2127400,
    populationYear: 2024,
    gdpPerCapitaUsd: 34301,
    gdpYear: 2024,
    tradeSummary: 'Küçük fakat yüksek gelirli AB pazarı; kalite ve güvenilirlik vurgusu fiyat kadar önemlidir.',
    babyKidsClothingSignal: 'Ljubljana ve Maribor butik çocuk giyim için az ama daha seçici lead üretebilir.',
    salesNotes: ['Slovence keywordler kullanılmalı.', 'Profesyonel web sitesi olan mağazalar önceliklendirilmeli.', 'Kalite sertifikası ve katalog sunumu önemli.'],
  },
  TR: {
    population: 85518661,
    populationYear: 2024,
    gdpPerCapitaUsd: 15893,
    gdpYear: 2024,
    tradeSummary: 'Çok büyük iç pazar ve güçlü tekstil üretim altyapısı var; rekabet yüksek ama hacim de yüksek.',
    babyKidsClothingSignal: 'Istanbul, Bursa ve Izmir çocuk/bebek giyim için hem üretici hem perakendeci yoğunluğu sağlar.',
    salesNotes: ['İstanbul semt bazlı parçalanarak taranmalı.', 'Bursa üretim/wholesale bağlantıları için ayrıca izlenebilir.', 'Farklılaşma ürün kalitesi ve hızlı stokla yapılmalı.'],
  },
  UA: {
    population: 37860221,
    populationYear: 2024,
    gdpPerCapitaUsd: 5389,
    gdpYear: 2024,
    tradeSummary: 'Büyük nüfuslu fakat bölgesel riskleri olan pazar. Batı ve merkez şehirleri daha kontrollü pilot alanlar olabilir.',
    babyKidsClothingSignal: 'Kyiv ve Lviv çocuk giyim mağazası keşfi için en güçlü başlangıç noktalarıdır.',
    salesNotes: ['Ukraynaca keywordler kullanılmalı.', 'Lviv ve Kyiv ayrı pilot yapılmalı.', 'Lojistik/ödeme koşulları lead notuna eklenmeli.'],
  },
  RU: {
    population: 143533851,
    populationYear: 2024,
    gdpPerCapitaUsd: 14889,
    gdpYear: 2024,
    tradeSummary: 'Çok büyük nüfus ve şehir hacmi var; ancak ödeme, lojistik ve yaptırım riski ayrıca değerlendirilmelidir.',
    babyKidsClothingSignal: 'Moscow ve Saint Petersburg yüksek lead hacmi verir; bölgesel şehirler fiyat odaklı olabilir.',
    salesNotes: ['Rusça keywordler zorunlu.', 'Ödeme ve teslimat uygunluğu ilk temas öncesi kontrol edilmeli.', 'Büyük şehirler segmentlere ayrılarak taranmalı.'],
  },
  MD: {
    population: 2402306,
    populationYear: 2024,
    gdpPerCapitaUsd: 7576,
    gdpYear: 2024,
    tradeSummary: 'Küçük fakat Romanya ve BDT hattına yakın, fiyat duyarlı bir pazar.',
    babyKidsClothingSignal: 'Chisinau çocuk/bebek giyim mağazaları için ana keşif alanıdır.',
    salesNotes: ['Romence ve Rusça aramalar birlikte denenmeli.', 'Küçük parti teklifleri avantajlı olur.', 'Telefon/WhatsApp bulunan mağazalar önceliklendirilmeli.'],
  },
  PL: {
    population: 36559233,
    populationYear: 2024,
    gdpPerCapitaUsd: 25104,
    gdpYear: 2024,
    tradeSummary: 'Büyük AB pazarı, yüksek perakende yoğunluğu ve güçlü e-ticaret alışkanlığı ile önemli hedef ülke.',
    babyKidsClothingSignal: 'Warsaw, Krakow ve Wroclaw çocuk giyim mağazaları için yüksek potansiyelli şehirlerdir.',
    salesNotes: ['Lehçe keywordler kullanılmalı.', 'Web sitesi olan mağazalar yüksek kalite sinyali sayılmalı.', 'AB etiket/kalite beklentileri net hazırlanmalı.'],
  },
  BY: {
    population: 9132629,
    populationYear: 2024,
    gdpPerCapitaUsd: 8318,
    gdpYear: 2024,
    tradeSummary: 'Orta ölçekli, Rusça ticari iletişimin güçlü olduğu ve ödeme/lojistik riskleri izlenmesi gereken pazar.',
    babyKidsClothingSignal: 'Minsk ana hacmi sağlar; Gomel ve Brest ikinci dalga için izlenebilir.',
    salesNotes: ['Rusça keywordler öncelikli.', 'Minsk pilot taraması yapılmalı.', 'Teslimat ve ödeme notu lead profilinde tutulmalı.'],
  },
  GE: {
    population: 3699557,
    populationYear: 2024,
    gdpPerCapitaUsd: 9241,
    gdpYear: 2024,
    tradeSummary: 'Kafkasya’da ithalata açık, Tbilisi ve Batumi etrafında yoğunlaşan niş perakende pazarı.',
    babyKidsClothingSignal: 'Tbilisi ana merkez, Batumi sezonluk/turistik perakende için ek fırsat sunar.',
    salesNotes: ['Gürcüce ve İngilizce aramalar birlikte çalıştırılmalı.', 'Tbilisi ilk pilot olmalı.', 'Instagram aktif mağazalar sıcak lead sayılmalı.'],
  },
  AM: {
    population: 3033500,
    populationYear: 2024,
    gdpPerCapitaUsd: 8556,
    gdpYear: 2024,
    tradeSummary: 'Küçük ama başkent odaklı, butik perakende ve ithal ürünlere açık pazar.',
    babyKidsClothingSignal: 'Yerevan çocuk/bebek giyim leadlerinin büyük kısmını üretir.',
    salesNotes: ['Ermenice keywordler denenmeli.', 'Yerevan sonrası Gyumri eklenmeli.', 'Düşük MOQ ve hızlı katalog paylaşımı avantaj sağlar.'],
  },
  AZ: {
    population: 10202830,
    populationYear: 2024,
    gdpPerCapitaUsd: 7284,
    gdpYear: 2024,
    tradeSummary: 'Türkiye ile dil/ticaret yakınlığı olan, Baku merkezli güçlü perakende fırsatı sunan pazar.',
    babyKidsClothingSignal: 'Baku çocuk/bebek giyim için ana hacmi verir; Ganja ve Sumqayit ikinci dalga olabilir.',
    salesNotes: ['Azerice ve Türkçe keywordler birlikte kullanılmalı.', 'Baku leadleri önceliklendirilmeli.', 'Türkçe iletişim avantajı değerlendirilmeli.'],
  },
  KZ: {
    population: 20592571,
    populationYear: 2024,
    gdpPerCapitaUsd: 14155,
    gdpYear: 2024,
    tradeSummary: 'Orta Asya’nın en güçlü gelir ölçeklerinden biri; büyük şehirler arası mesafe nedeniyle şehir bazlı planlama gerekir.',
    babyKidsClothingSignal: 'Almaty ve Astana çocuk giyim mağazaları için yüksek potansiyelli başlangıç şehirleridir.',
    salesNotes: ['Rusça ve Kazakça keywordler birlikte çalıştırılmalı.', 'Almaty/Astana ayrı kampanya gibi ele alınmalı.', 'Lojistik maliyeti teklif notuna eklenmeli.'],
  },
  UZ: {
    population: 36361859,
    populationYear: 2024,
    gdpPerCapitaUsd: 3162,
    gdpYear: 2024,
    tradeSummary: 'Büyük ve genç nüfuslu, fiyat hassasiyeti yüksek fakat hacim potansiyeli güçlü pazar.',
    babyKidsClothingSignal: 'Tashkent ana merkez; Samarkand, Namangan ve Andijan ikinci dalga için önemlidir.',
    salesNotes: ['Özbekçe ve Rusça keywordler birlikte kullanılmalı.', 'Fiyat aralığı net sunulmalı.', 'Yüksek hacim/düşük birim fiyat senaryosu değerlendirilmeli.'],
  },
  KG: {
    population: 7221868,
    populationYear: 2024,
    gdpPerCapitaUsd: 2420,
    gdpYear: 2024,
    tradeSummary: 'Fiyat odaklı, küçük/orta ölçekli perakende ağına sahip gelişen pazar.',
    babyKidsClothingSignal: 'Bishkek ana lead merkezi; Osh ikinci dalga için eklenebilir.',
    salesNotes: ['Rusça keywordler başlangıç için yeterli olabilir.', 'Düşük MOQ önemli.', 'WhatsApp iletişimi öncelikli tutulmalı.'],
  },
  TJ: {
    population: 10590927,
    populationYear: 2024,
    gdpPerCapitaUsd: 1341,
    gdpYear: 2024,
    tradeSummary: 'Düşük gelirli fakat genç nüfuslu; fiyat ve temel ürün grupları daha kritik olan pazar.',
    babyKidsClothingSignal: 'Dushanbe en anlamlı başlangıç noktasıdır; diğer şehirler düşük hacimli taranmalı.',
    salesNotes: ['Rusça ve Tacikçe keywordler denenmeli.', 'Ekonomik ürün segmenti öncelikli olmalı.', 'Lead kalitesi manuel kontrol gerektirir.'],
  },
  TM: {
    population: 7494498,
    populationYear: 2024,
    gdpPerCapitaUsd: 6857,
    gdpYear: 2024,
    tradeSummary: 'Kapalı ve ilişki bazlı ilerleyen bir pazar; Ashgabat merkezli leadler daha dikkatli manuel kontrol edilmeli.',
    babyKidsClothingSignal: 'Ashgabat ana başlangıç noktasıdır; Rusça ve Türkmençe aramalar birlikte denenmelidir.',
    salesNotes: ['Ashgabat ilk pilot olmalı.', 'Rusça arama çoğu zaman daha çok sonuç verir.', 'Ödeme/lojistik uygunluğu ilk temas öncesi kontrol edilmeli.'],
  },
  'RU-DA': {
    population: 143533851,
    populationYear: 2024,
    gdpPerCapitaUsd: 14889,
    gdpYear: 2024,
    tradeSummary: 'Rusya makro pazarı içinde Kafkasya odaklı bölgesel satış noktası. Makhachkala ve Derbent perakende keşfi için öncelikli.',
    babyKidsClothingSignal: 'Aile ve çocuk odaklı tüketim güçlü olabilir; çocuk giyim mağazaları şehir merkezlerinde aranmalı.',
    salesNotes: ['Makhachkala ilk pilot şehir olmalı.', 'Rusça keywordler ana kanal.', 'Dağıstan leadleri Rusya bölgesel segmenti olarak ayrı takip edilmeli.'],
  },
  'RU-CE': {
    population: 143533851,
    populationYear: 2024,
    gdpPerCapitaUsd: 14889,
    gdpYear: 2024,
    tradeSummary: 'Grozny merkezli bölgesel pazar. Rusya ticaret koşulları geçerli, fakat yerel perakende ağı ayrı ele alınmalı.',
    babyKidsClothingSignal: 'Grozny çocuk/bebek giyim mağazaları için ana keşif noktasıdır.',
    salesNotes: ['Grozny pilot taraması yapılmalı.', 'Telefon/WhatsApp olan mağazalar önceliklendirilmeli.', 'Rusça kısa satış metni kullanılmalı.'],
  },
  'RU-IN': {
    population: 143533851,
    populationYear: 2024,
    gdpPerCapitaUsd: 14889,
    gdpYear: 2024,
    tradeSummary: 'Küçük ama Kafkasya hattında tamamlayıcı satış bölgesi. Lead hacmi düşük, manuel kalite kontrol önemli.',
    babyKidsClothingSignal: 'Nazran ve Magas etrafında çocuk giyim mağazaları aranmalı.',
    salesNotes: ['Nazran başlangıç noktası olabilir.', 'Az lead beklenmeli ama telefonlu leadler değerlidir.', 'Dağıstan/Çeçenistan ile birlikte kampanya yapılabilir.'],
  },
  'RU-SE': {
    population: 143533851,
    populationYear: 2024,
    gdpPerCapitaUsd: 14889,
    gdpYear: 2024,
    tradeSummary: 'Vladikavkaz merkezli Kuzey Kafkasya pazarı; bölgesel perakende mağazaları ayrı izlenmeli.',
    babyKidsClothingSignal: 'Vladikavkaz çocuk giyim mağazaları için en güçlü başlangıç şehridir.',
    salesNotes: ['Vladikavkaz pilot yapılmalı.', 'Rusça keywordler kullanılmalı.', 'Kafkasya bölge paketi içinde takip edilebilir.'],
  },
  'RU-TA': {
    population: 143533851,
    populationYear: 2024,
    gdpPerCapitaUsd: 14889,
    gdpYear: 2024,
    tradeSummary: 'Kazan merkezli güçlü bölgesel pazar. Rusya içinde gelir ve şehir ölçeği açısından daha nitelikli lead üretebilir.',
    babyKidsClothingSignal: 'Kazan ve Naberezhnye Chelny çocuk giyim mağazası aramaları için yüksek potansiyelli.',
    salesNotes: ['Kazan ilk pilot olmalı.', 'Rusça ve Tatarca keywordler birlikte denenmeli.', 'Website olan mağazalar sıcak lead kabul edilmeli.'],
  },
  'RU-BA': {
    population: 143533851,
    populationYear: 2024,
    gdpPerCapitaUsd: 14889,
    gdpYear: 2024,
    tradeSummary: 'Ufa merkezli büyük bölgesel pazar; Tataristan ile birlikte Volga-Ural hattı olarak çalışılabilir.',
    babyKidsClothingSignal: 'Ufa ve Sterlitamak çocuk/bebek giyim leadleri için ana şehirlerdir.',
    salesNotes: ['Ufa pilot yapılmalı.', 'Rusça keywordler yeterli başlangıç sağlar.', 'Tataristan ile aynı satış kampanyasına bağlanabilir.'],
  },
};
